version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "4001:4001"
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    logging:
      driver: "none"
    ports:
      - '5438:5432'
    volumes:
      - postgres:/data/postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    logging:
        driver: "none"
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
        GUNICORN_ACCESS_LOGFILE: "/tmp/log.txt"
    ports:
        - "5050:80"
volumes:
  server:
  postgres: